import type { SeedEntry } from './types.js';

export const FRONTEND_ENTRIES: SeedEntry[] = [
  { id: 'fe1', cat: '前端', title: '闭包', py: 'bibao bb closure', tags: ['JS', '作用域'], summary: '函数能记住并访问其词法作用域，即使在作用域外执行。', body: '闭包是指**函数**能够访问其定义时所在的词法作用域，即便该函数在其他位置被调用。\n\n## 形成条件\n- 函数嵌套\n- 内部函数引用了外部函数的变量\n- 内部函数被返回或传递到外部\n\n## 常见用途\n- 数据私有化（模块模式）\n- 函数柯里化、防抖节流\n- 保存循环中的状态\n\n```js\nfunction counter() {\n  let n = 0;\n  return () => ++n;\n}\n```\n\n注意：闭包会延长变量生命周期，使用不当可能造成内存泄漏。' },
  { id: 'fe2', cat: '前端', title: '事件循环', py: 'shijianxunhuan sjxh eventloop', tags: ['JS', '异步'], summary: '宏任务 / 微任务的执行机制，决定异步代码的执行顺序。', body: 'JS 是单线程的，通过**事件循环**处理异步。\n\n## 执行顺序\n- 执行同步代码（调用栈）\n- 清空所有**微任务**（Promise.then、queueMicrotask）\n- 取一个**宏任务**（setTimeout、I/O、事件）\n- 重复\n\n## 关键点\n- 每个宏任务后都会清空微任务队列\n- `async/await` 本质是 Promise 的语法糖\n- 微任务优先级高于宏任务' },
  { id: 'fe3', cat: '前端', title: '原型链', py: 'yuanxinglian yxl prototype', tags: ['JS'], summary: '对象通过 __proto__ 逐级向上查找属性，构成继承链。', body: '每个对象都有一个内部指针 `__proto__` 指向其构造函数的 `prototype`。\n\n## 查找过程\n- 访问属性时，先查自身\n- 找不到则沿 `__proto__` 向上\n- 直到 `Object.prototype`，再上是 `null`\n\n## 要点\n- `instanceof` 基于原型链判断\n- `class` 是原型继承的语法糖\n- `Object.create(proto)` 显式指定原型' },
  { id: 'fe4', cat: '前端', title: '防抖与节流', py: 'fangdoujieliu fdjl debounce throttle', tags: ['JS', '性能'], summary: '控制高频事件触发频率的两种优化手段。', body: '## 防抖 debounce\n触发后等待一段时间，期间再次触发则重新计时。适合：搜索输入、窗口 resize。\n\n## 节流 throttle\n固定时间间隔内只执行一次。适合：滚动加载、按钮防连点。\n\n```js\nconst debounce = (fn, t) => {\n  let timer;\n  return (...a) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...a), t);\n  };\n};\n```' },
  { id: 'fe5', cat: '前端', title: '虚拟 DOM', py: 'xunidom xndom vdom virtualdom', tags: ['框架'], summary: '用 JS 对象描述 DOM，通过 diff 计算最小更新。', body: '虚拟 DOM 是用 JS 对象对真实 DOM 的轻量描述。\n\n## 优势\n- 批量、最小化真实 DOM 操作\n- 跨平台（可渲染到原生、canvas）\n- 声明式编程\n\n## diff 策略\n- 同层比较，不跨层级\n- 通过 `key` 复用同类节点\n- 类型不同直接替换子树' },
  { id: 'fe6', cat: '前端', title: '重排与重绘', py: 'zhongpaizhonghui zpzh reflow repaint', tags: ['浏览器', '性能'], summary: 'reflow 重新计算布局，repaint 重新绘制像素。', body: '## 重排 reflow\n几何属性变化（宽高、位置）触发，开销大，会引起重绘。\n\n## 重绘 repaint\n仅样式变化（颜色、背景），不影响布局。\n\n## 优化\n- 批量修改样式（用 class 切换）\n- 读写分离，避免强制同步布局\n- 使用 `transform`/`opacity` 走合成层' },
  { id: 'fe7', cat: '前端', title: '跨域与 CORS', py: 'kuayu ky cors', tags: ['网络'], summary: '同源策略限制，及 CORS、代理等解决方案。', body: '浏览器**同源策略**限制不同源（协议+域名+端口）的请求。\n\n## 解决方案\n- **CORS**：服务端设置 `Access-Control-Allow-Origin`\n- **代理**：开发用 devServer，生产用 Nginx\n- **JSONP**：仅支持 GET（老方案）\n\n## 预检请求\n非简单请求会先发 `OPTIONS` 预检。' },
  { id: 'fe8', cat: '前端', title: 'CSS 盒模型', py: 'hemoxing hmx boxmodel', tags: ['CSS'], summary: 'content / padding / border / margin 的尺寸计算。', body: '## 标准盒模型\n`width` 只含内容区，总宽 = width + padding + border。\n\n## 怪异盒模型\n`box-sizing: border-box`，width 包含 padding 和 border，更直观。\n\n推荐全局设置 `* { box-sizing: border-box; }`。' },
];
